"""Public package interface for ai-native-cfd."""

from aicfd.amr import (
    GeometryLevelFloor,
    Indicator,
    IndicatorResult,
    LevelFloor,
    NeighborJumpIndicator,
    SolutionAdaptationReport,
    SolutionRefinementPolicy,
    ValueRangeIndicator,
    WaveletDetailIndicator,
    adapt_solution,
    combine_indicators,
)
from aicfd.fields import (
    CellField,
    FieldLocation,
    FieldSpec,
    MeasureProvider,
    State,
    TopologyAdaptationReport,
    TreeLayout,
    ValueRepresentation,
    adapt_state_topology,
    field_total,
    load_checkpoint,
    measures_from_provider,
    remap_state,
    write_checkpoint,
)
from aicfd.geometry import (
    AdaptationReport,
    BoundarySample2D,
    BoundaryVertex2D,
    CellClassification,
    DistanceBand,
    GeometryRefinementPolicy,
    Obstacle2D,
    SnappedCell2D,
    SnappedGeometry2D,
    adapt_to_obstacle,
    snap_to_obstacle,
)
from aicfd.representation import AdaptiveTree, Cell

__all__ = [
    "AdaptationReport",
    "AdaptiveTree",
    "BoundarySample2D",
    "BoundaryVertex2D",
    "Cell",
    "CellField",
    "CellClassification",
    "DistanceBand",
    "FieldLocation",
    "FieldSpec",
    "GeometryLevelFloor",
    "GeometryRefinementPolicy",
    "Indicator",
    "IndicatorResult",
    "LevelFloor",
    "MeasureProvider",
    "NeighborJumpIndicator",
    "Obstacle2D",
    "SnappedCell2D",
    "SnappedGeometry2D",
    "State",
    "SolutionAdaptationReport",
    "SolutionRefinementPolicy",
    "TopologyAdaptationReport",
    "TreeLayout",
    "ValueRepresentation",
    "ValueRangeIndicator",
    "WaveletDetailIndicator",
    "adapt_state_topology",
    "adapt_solution",
    "adapt_to_obstacle",
    "combine_indicators",
    "field_total",
    "load_checkpoint",
    "measures_from_provider",
    "remap_state",
    "snap_to_obstacle",
    "write_checkpoint",
]
__version__ = "0.1.0"
